### ISSUE TITLE
dist/index.html

### ISSUE THREAD

**Issue by bj1024** [rdlabo/spa_bootstrap_time#3]
Angular2、なぜかビルドがうまく行きません。
どなたかビルドしてdist/index.html と周辺パックファイルをcommitいただけると幸いです。

**Comment by rdlabo** [comment]
あら。angular-cli使ってもビルドできませんかー？？

**Comment by bj1024** [comment]
なぜかうまく行きません…追いかけてる時間がなく…
原因は後ほど探ってみます。

**Comment by rdlabo** [comment]
エラーメッセージ吐いてたら、貼り付けておいてくださいー。

**Comment by bj1024** [comment]
なぜかこういうのが多量にでてます。

ERROR in ./src/main.ts
Module not found: Error: Can't resolve '@angular/platform-browser-dynamic' in '/Users/dev/develop/rdlabo_spa_bootstrap_time/angular-2.0/src'
 @ ./src/main.ts 2:0-75
 @ multi main

**Comment by rdlabo** [comment]
npm i しなきゃいけないとか、そういうオチ・・・？

**Comment by bj1024** [comment]
やってるんですが…なんだろ。ｗ。まだ追いかけてないです。

**Comment by bj1024** [comment]
よくわかりませんが、npm install -g angular-cli を3回やったら治りました…
一応ビルドできました。
